{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: dataviz-secrets
  labels:
    {{- include "dataviz.labels" . | nindent 4 }}
type: Opaque
stringData:
  MANAGEMENT_DB_URL: {{ .Values.secrets.managementDbUrl | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  CREDENTIAL_ENCRYPTION_KEY: {{ .Values.secrets.credentialEncryptionKey | quote }}
{{- end }}
